name: MMR Client Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Remove .env file
        run: rm -f .env

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Remove .next folder
        run: rm -rf .next

      - name: Build
        run: npm run build

      # Check if PM2 process is running
      - name: Check PM2 process status
        id: pm2_status
        run: |
          pm2 show "mmr_client" || echo "not_running"

      # Delete PM2 process if it is running
      - name: Delete PM2 process
        if: steps.pm2_status.outputs.pm2_status != 'not_running'
        run: pm2 delete "mmr_client" || echo "not running, nothing to delete"

      - name: Deploy
        run: pm2 start npm --name "mmr_client" -- start

      - name: Check status
        run: pm2 status

      - name: Save logs
        run: pm2 save
